"""empty message

Revision ID: 0b19af10736f
Revises: 13dad47f4dbe
Create Date: 2022-11-23 20:50:53.208942

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0b19af10736f'
down_revision = '13dad47f4dbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_bills', sa.Column('bill_number', sa.String(length=11), nullable=False))
    op.add_column('test_bills', sa.Column('pan', sa.String(length=10), nullable=False))
    op.add_column('test_bills', sa.Column('bill_item', sa.String(length=40), nullable=False))
    op.add_column('test_bills', sa.Column('item_cost', sa.Float(), nullable=True))
    op.drop_index('ix_test_bills_bill_no', table_name='test_bills')
    op.create_index(op.f('ix_test_bills_bill_number'), 'test_bills', ['bill_number'], unique=False)
    op.create_index(op.f('ix_test_bills_pan'), 'test_bills', ['pan'], unique=False)
    op.drop_column('test_bills', 'bill_no')
    op.drop_column('test_bills', 'bill_date')
    op.drop_column('test_bills', 'quantity')
    op.drop_column('test_bills', 'price')
    op.drop_column('test_bills', 'cost')
    op.drop_column('test_bills', 'user_name')
    op.drop_column('test_bills', 'item')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_bills', sa.Column('item', mysql.VARCHAR(length=40), nullable=False))
    op.add_column('test_bills', sa.Column('user_name', mysql.VARCHAR(length=40), nullable=False))
    op.add_column('test_bills', sa.Column('cost', mysql.FLOAT(), nullable=True))
    op.add_column('test_bills', sa.Column('price', mysql.FLOAT(), nullable=True))
    op.add_column('test_bills', sa.Column('quantity', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('test_bills', sa.Column('bill_date', mysql.DATETIME(), nullable=False))
    op.add_column('test_bills', sa.Column('bill_no', mysql.VARCHAR(length=11), nullable=False))
    op.drop_index(op.f('ix_test_bills_pan'), table_name='test_bills')
    op.drop_index(op.f('ix_test_bills_bill_number'), table_name='test_bills')
    op.create_index('ix_test_bills_bill_no', 'test_bills', ['bill_no'], unique=False)
    op.drop_column('test_bills', 'item_cost')
    op.drop_column('test_bills', 'bill_item')
    op.drop_column('test_bills', 'pan')
    op.drop_column('test_bills', 'bill_number')
    # ### end Alembic commands ###
