"""Initial Migration

Revision ID: 11f32150cf0f
Revises: 
Create Date: 2022-09-19 21:49:27.879411

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '11f32150cf0f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_address_customer_name', table_name='address')
    op.drop_table('address')
    op.drop_index('ix_user_fullname', table_name='user')
    op.drop_table('user')
    op.drop_table('transactions')
    op.drop_index('ix_tax_info_aadhaar', table_name='tax_info')
    op.drop_index('ix_tax_info_customer_name', table_name='tax_info')
    op.drop_index('ix_tax_info_pan', table_name='tax_info')
    op.drop_table('tax_info')
    op.drop_index('ix_customer_firstname', table_name='customer')
    op.drop_index('ix_customer_fullname', table_name='customer')
    op.drop_index('ix_customer_lastname', table_name='customer')
    op.drop_table('customer')
    op.add_column('test_users', sa.Column('firstname', sa.String(length=20), nullable=False))
    op.add_column('test_users', sa.Column('lastname', sa.String(length=20), nullable=False))
    op.add_column('test_users', sa.Column('email', sa.String(length=30), nullable=True))
    op.add_column('test_users', sa.Column('phone', sa.String(length=10), nullable=True))
    op.add_column('test_users', sa.Column('username', sa.String(length=6), nullable=False))
    op.drop_column('test_users', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_users', sa.Column('name', mysql.VARCHAR(length=30), nullable=True))
    op.drop_column('test_users', 'username')
    op.drop_column('test_users', 'phone')
    op.drop_column('test_users', 'email')
    op.drop_column('test_users', 'lastname')
    op.drop_column('test_users', 'firstname')
    op.create_table('customer',
                    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
                    sa.Column('fullname', mysql.VARCHAR(length=30), nullable=False),
                    sa.Column('email', mysql.VARCHAR(length=30), nullable=True),
                    sa.Column('phone', mysql.VARCHAR(length=10), nullable=True),
                    sa.Column('firstname', mysql.VARCHAR(length=15), nullable=True),
                    sa.Column('lastname', mysql.VARCHAR(length=15), nullable=True),
                    sa.Column('type', mysql.ENUM('personal', 'commercial'), nullable=False),
                    sa.Column('date_added', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'),
                              nullable=False),
                    sa.Column('date_updated', mysql.DATETIME(), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    mysql_collate='utf8mb4_0900_ai_ci',
                    mysql_default_charset='utf8mb4',
                    mysql_engine='InnoDB'
                    )
    op.create_table('tax_info',
                    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
                    sa.Column('customer_id', mysql.INTEGER(), autoincrement=False, nullable=False),
                    sa.Column('customer_name', mysql.VARCHAR(length=30), nullable=False),
                    sa.Column('pan', mysql.VARCHAR(length=12), nullable=False),
                    sa.Column('aadhaar', mysql.VARCHAR(length=12), nullable=False),
                    sa.Column('date_added', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'),
                              nullable=False),
                    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], name='tax_info_ibfk_1',
                                            onupdate='CASCADE', ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id'),
                    mysql_collate='utf8mb4_0900_ai_ci',
                    mysql_default_charset='utf8mb4',
                    mysql_engine='InnoDB'
                    )
    op.create_index('ix_tax_info_pan', 'tax_info', ['pan'], unique=False)
    op.create_index('ix_tax_info_customer_name', 'tax_info', ['customer_name'], unique=False)
    op.create_index('ix_tax_info_aadhaar', 'tax_info', ['aadhaar'], unique=False)
    op.create_index('ix_customer_lastname', 'customer', ['lastname'], unique=False)
    op.create_index('ix_customer_fullname', 'customer', ['fullname'], unique=False)
    op.create_index('ix_customer_firstname', 'customer', ['firstname'], unique=False)
    op.create_table('user',
                    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
                    sa.Column('firstname', mysql.VARCHAR(length=15), nullable=True),
                    sa.Column('lastname', mysql.VARCHAR(length=15), nullable=True),
                    sa.Column('fullname', mysql.VARCHAR(length=30), nullable=True),
                    sa.Column('email', mysql.VARCHAR(length=30), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    mysql_collate='utf8mb4_0900_ai_ci',
                    mysql_default_charset='utf8mb4',
                    mysql_engine='InnoDB'
                    )
    op.create_table('transactions',
                    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
                    sa.Column('date', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
                    sa.Column('customer_id', mysql.INTEGER(), autoincrement=False, nullable=False),
                    sa.Column('transaction_type', mysql.VARCHAR(length=50), nullable=False),
                    sa.Column('amount', mysql.FLOAT(), nullable=True),
                    sa.Column('status', mysql.ENUM('pending', 'complete', 'failed'),
                              server_default=sa.text("'pending'"), nullable=False),
                    sa.Column('paid_on', mysql.DATETIME(), nullable=True),
                    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], name='transactions_ibfk_1',
                                            onupdate='CASCADE', ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id'),
                    mysql_collate='utf8mb4_0900_ai_ci',
                    mysql_default_charset='utf8mb4',
                    mysql_engine='InnoDB'
                    )

    op.create_index('ix_user_fullname', 'user', ['fullname'], unique=False)
    op.create_table('address',
                    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
                    sa.Column('customer_id', mysql.INTEGER(), autoincrement=False, nullable=False),
                    sa.Column('customer_name', mysql.VARCHAR(length=30), nullable=True),
                    sa.Column('street_num', mysql.VARCHAR(length=8), nullable=True),
                    sa.Column('street_name', mysql.VARCHAR(length=30), nullable=True),
                    sa.Column('house_num', mysql.VARCHAR(length=8), nullable=True),
                    sa.Column('locality', mysql.VARCHAR(length=30), nullable=True),
                    sa.Column('city', mysql.VARCHAR(length=20), nullable=False),
                    sa.Column('state', mysql.VARCHAR(length=15), server_default=sa.text("'Tamil Nadu'"),
                              nullable=False),
                    sa.Column('pin', mysql.VARCHAR(length=6), nullable=False),
                    sa.Column('date_added', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'),
                              nullable=False),
                    sa.Column('last_update', mysql.DATETIME(), nullable=True),
                    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], name='address_ibfk_1', onupdate='CASCADE',
                                            ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id'),
                    mysql_collate='utf8mb4_0900_ai_ci',
                    mysql_default_charset='utf8mb4',
                    mysql_engine='InnoDB'
                    )
    op.create_index('ix_address_customer_name', 'address', ['customer_name'], unique=False)
    # ### end Alembic commands ###
