"""add separate contact table

Revision ID: 14aeca5a2fa8
Revises: 4e73354895da
Create Date: 2022-11-14 15:34:13.084831

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '14aeca5a2fa8'
down_revision = '4e73354895da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_test_customers_email', table_name='test_customers')
    op.drop_column('test_customers', 'email')
    op.drop_column('test_customers', 'phone')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_customers', sa.Column('phone', mysql.VARCHAR(length=14), nullable=True))
    op.add_column('test_customers', sa.Column('email', mysql.VARCHAR(length=30), nullable=True))
    op.create_index('ix_test_customers_email', 'test_customers', ['email'], unique=False)
    # ### end Alembic commands ###
