"""change FK column

Revision ID: 3c46dcb91fc5
Revises: 4b9c91b33626
Create Date: 2022-11-24 16:27:24.181429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c46dcb91fc5'
down_revision = '4b9c91b33626'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint('test_items_ibfk_1', 'test_items', type_='foreignkey')
    op.create_foreign_key(None, 'test_items', 'test_bills', ['bill_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'test_items', type_='foreignkey')
    op.create_foreign_key('test_items_ibfk_1', 'test_items', 'test_bills', ['bill_id'], ['bill_number'], ondelete='CASCADE')
    # ### end Alembic commands ###
