"""empty message

Revision ID: 442abd748d6e
Revises: 11f32150cf0f
Create Date: 2022-09-20 17:13:56.108787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '442abd748d6e'
down_revision = '11f32150cf0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_users', 'username')
    op.add_column('test_users', sa.Column('username', sa.String(length=20), nullable=False))
    op.add_column('test_users', sa.Column('password_hash', sa.String(length=60), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_users', 'password_hash')
    op.drop_column('test_users', 'username')
    op.add_column('test_users', sa.Column('username', sa.String(length=6), nullable=False))
    # ### end Alembic commands ###
