"""separate item and bill tables

Revision ID: 4b9c91b33626
Revises: 0b19af10736f
Create Date: 2022-11-23 23:06:10.452401

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4b9c91b33626'
down_revision = '0b19af10736f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_bills', 'item_cost')
    op.drop_column('test_bills', 'bill_item')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_bills', sa.Column('bill_item', mysql.VARCHAR(length=40), nullable=False))
    op.add_column('test_bills', sa.Column('item_cost', mysql.FLOAT(), nullable=True))
    # ### end Alembic commands ###
