"""change address type enum

Revision ID: 4e73354895da
Revises: 839fe6b6fc9c
Create Date: 2022-11-14 14:40:43.358551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e73354895da'
down_revision = '839fe6b6fc9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_address', sa.Column('locality_2', sa.String(length=30), nullable=True))
    op.add_column('test_identity', sa.Column('added_user', sa.String(length=20), nullable=True))
    op.add_column('test_identity', sa.Column('date_added', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('test_identity', sa.Column('updated_user', sa.String(length=20), nullable=True))
    op.add_column('test_identity', sa.Column('last_update', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_identity', 'last_update')
    op.drop_column('test_identity', 'updated_user')
    op.drop_column('test_identity', 'date_added')
    op.drop_column('test_identity', 'added_user')
    op.drop_column('test_address', 'locality_2')
    # ### end Alembic commands ###
