"""add foreign keys

Revision ID: 6347e96e55a9
Revises: 989b68ead7df
Create Date: 2022-10-24 22:06:13.942056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6347e96e55a9'
down_revision = '989b68ead7df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_address', sa.Column('customer_id', sa.Integer(), nullable=False))
    op.create_foreign_key('fk_address_customer_id', 'test_address', 'test_customers',
                          ['customer_id'], ['id'],
                          onupdate='CASCADE', ondelete='CASCADE')
    op.add_column('test_taxinfo', sa.Column('customer_id', sa.Integer(), nullable=False))
    op.create_foreign_key('fk_taxinfo_customer_id', 'test_taxinfo', 'test_customers',
                          ['customer_id'], ['id'],
                          onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_taxinfo_customer_id', 'test_taxinfo', type_='foreignkey')
    op.drop_column('test_taxinfo', 'customer_id')
    op.drop_constraint('fk_address_customer_id', 'test_address', type_='foreignkey')
    op.drop_column('test_address', 'customer_id')
    # ### end Alembic commands ###
