"""add fields to customer table

Revision ID: 772ff40e598c
Revises: 442abd748d6e
Create Date: 2022-10-08 14:24:50.647866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '772ff40e598c'
down_revision = '442abd748d6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_customers', sa.Column('added_user', sa.String(length=20), nullable=True))
    op.add_column('test_customers', sa.Column('updated_user', sa.String(length=20), nullable=True))
    op.create_index(op.f('ix_test_customers_email'), 'test_customers', ['email'], unique=False)
    op.create_index(op.f('ix_test_customers_fullname'), 'test_customers', ['fullname'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_test_customers_fullname'), table_name='test_customers')
    op.drop_index(op.f('ix_test_customers_email'), table_name='test_customers')
    op.drop_column('test_customers', 'updated_user')
    op.drop_column('test_customers', 'added_user')
    # ### end Alembic commands ###
