"""remove customer name foreign key

Revision ID: 839fe6b6fc9c
Revises: 6347e96e55a9
Create Date: 2022-10-29 00:11:53.202222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '839fe6b6fc9c'
down_revision = '6347e96e55a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('test_identity_ibfk_2', 'test_identity', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('test_identity_ibfk_2', 'test_identity', 'test_customers', ['customer_name'], ['fullname'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###
