"""remove foreign keys

Revision ID: 989b68ead7df
Revises: f986eff10ea6
Create Date: 2022-10-24 18:12:51.406494

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '989b68ead7df'
down_revision = 'f986eff10ea6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('test_address_ibfk_1', 'test_address', type_='foreignkey')
    op.drop_column('test_address', 'customer_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_address', sa.Column('customer_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('test_address_ibfk_1', 'test_address', 'test_customers', ['customer_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###
