"""add billing table and username is unique

Revision ID: cd7188e63e10
Revises: 14aeca5a2fa8
Create Date: 2022-11-16 10:38:08.603734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd7188e63e10'
down_revision = '14aeca5a2fa8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_taxinfo', sa.Column('filed_by', sa.String(length=20), nullable=False))
    op.add_column('test_taxinfo', sa.Column('filed_on', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_test_taxinfo_filed_by'), 'test_taxinfo', ['filed_by'], unique=False)
    op.add_column('test_users', sa.Column('last_update', sa.DateTime(timezone=True), nullable=True))
    op.add_column('test_users', sa.Column('last_login', sa.DateTime(timezone=True), nullable=True))
    op.drop_index('ix_test_users_username', table_name='test_users')
    op.create_index(op.f('ix_test_users_username'), 'test_users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_test_users_username'), table_name='test_users')
    op.create_index('ix_test_users_username', 'test_users', ['username'], unique=False)
    op.drop_column('test_users', 'last_login')
    op.drop_column('test_users', 'last_update')
    op.drop_index(op.f('ix_test_taxinfo_filed_by'), table_name='test_taxinfo')
    op.drop_column('test_taxinfo', 'filed_on')
    op.drop_column('test_taxinfo', 'filed_by')
    # ### end Alembic commands ###
