"""change phone column size

Revision ID: f986eff10ea6
Revises: 772ff40e598c
Create Date: 2022-10-08 23:44:36.837511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f986eff10ea6'
down_revision = '772ff40e598c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_test_customers_firstname'), 'test_customers', ['firstname'], unique=False)
    op.create_index(op.f('ix_test_customers_lastname'), 'test_customers', ['lastname'], unique=False)
    op.create_index(op.f('ix_test_customers_type'), 'test_customers', ['type'], unique=False)
    op.add_column('test_users', sa.Column('fullname', sa.String(length=40), nullable=False))
    op.add_column('test_users', sa.Column('added_on', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('test_users', sa.Column('added_by', sa.String(length=20), nullable=True))
    op.create_index(op.f('ix_test_users_fullname'), 'test_users', ['fullname'], unique=False)
    op.create_index(op.f('ix_test_users_username'), 'test_users', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_test_users_username'), table_name='test_users')
    op.drop_index(op.f('ix_test_users_fullname'), table_name='test_users')
    op.drop_column('test_users', 'added_by')
    op.drop_column('test_users', 'added_on')
    op.drop_column('test_users', 'fullname')
    op.drop_index(op.f('ix_test_customers_type'), table_name='test_customers')
    op.drop_index(op.f('ix_test_customers_lastname'), table_name='test_customers')
    op.drop_index(op.f('ix_test_customers_firstname'), table_name='test_customers')
    # ### end Alembic commands ###
